version: '3.8'

services:
  service-portal-api-app:
    build: .
    
    container_name: service-portal-api-app-container
    ports:
      - "8282:8080"
    restart: always
    environment:
      # ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Production